import Head from 'next/head'
import { DarkModeSwitch } from '../components/DarkModeSwitch'
import { useMediaQuery, Avatar, List, ListItem, ListIcon,MdCheckCircle,Link,Text, Image, Stack,HStack,StackDivider,VStack,Box, Center  } from "@chakra-ui/react"
import { ExternalLinkIcon } from '@chakra-ui/icons'


export default function Home() {
  return (
    <Stack>
    
      <Head >
        <title>Mi portafolio</title>
        <meta name="myportfolioproect" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>


      <nav>
        <DarkModeSwitch/>
      </nav>


      <main>
      <Box />
      
        

        <Box h="100vh" clipPath="polygon(100% 0, 100% 50%, 100% 90%, 50% 100%, 0 90%, 0% 0%)" bgColor="cyan.900"> 
        <Center w="80%" flexDir="column">
        <Text fontSize="6xl" fontFamily="cursive">Mi Portafolio</Text>
        <br/>
        
        <Image
            borderRadius="full"
            boxSize="150px"
            src="https://scontent.fmex33-1.fna.fbcdn.net/v/t1.6435-9/37693347_220925092084311_7773108262718668800_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=174925&_nc_eui2=AeEkVv5yv-tc5O8nQlvvWgPtxk8IyK4KZ-zGTwjIrgpn7POJ9nok1TNC4spCPIyMAxrLDoS_XnDgT5sye5-KhEDY&_nc_ohc=4vXpe1pzIsUAX-ajf1F&_nc_ht=scontent.fmex33-1.fna&oh=ac80220724abc3e585c051b1a7fa2804&oe=613FA4E0"
            alt="foto de perfil claudio"
          />
        <br/>
        <Text fontSize="2rem">Mi nombre es Claudio Chametla y soy progrador web. </Text>
        </Center>
        </Box>
        
        






       
        <Box h="10px"/>

        <VStack
             
              spacing={1}
              align="stretch"
              
              
            >



          {/*-----------------------------------BIENVENIDO-------------------------------------------------------*/}
          <Box align="center"
              justify="center" 
              bgImage="" h="600px" w="100%" >
          <Center w="80%" flexDir="column">
            <Text fontSize="6xl" fontFamily="cursive"> Bienvenido </Text>
          <hr/>
          <Text 
            fontSize="20px" 
            fontFamily="sans-serif" 
            >Este en un espacio para mostrar 
          mi portafolio web el cual esta desarrollado en Next JS el cual es un Framework construido sobre React, la libreria 
          de Javascript. 
          <br/>
          Ademas utilizando la libreria de Chakra UI. 
          
          
          </Text>
          <Box h="100px"/>
          
              <Image borderRadius="full" w="250px" h="auto" src="https://static.vecteezy.com/system/resources/thumbnails/002/100/588/small/folder-of-documents-portfolio-with-files-linear-outline-business-icon-neon-style-light-decoration-icon-bright-electric-symbol-isolated-on-brick-wall-vector.jpg" alt="Imagen Portafolio" />
          
          </Center>
          
          </Box>
          {/*-----------------------------------FIN BIENVENIDO-------------------------------------------------------*/}

          {/*-----------------------------------PROYECTO-------------------------------------------------------*/}          
          <Box align="center"
              justify="center" h="600px">
          
            <Text fontSize="6xl" fontFamily="cursive" >Proyectos</Text>
            <Center  w="80%" flexDir="column">
            <Text 
              fontSize="20px" 
              >Algunos de mis proyectos estan hosteados en 
              Git Hub y CodePen ademas de mas información de mi perfil 
              laboral se puede encontrar en las siguientes plataformas. 
            <br/>
            Solo da un click para acceder a las diferentes plataformas donde encontraras mas información
            de mis proyectos, lo cuales incluyen direfentes sitios web y mas.   </Text>
            
            </Center>
            <br/>
            <br/>
            <VStack>
            <List spacing={5}>
            
           
                <ListItem fontSize="2rem" fontFamily="cursive"> 
                
                  Mis proyectos:
                </ListItem>
              
                <ListItem>
                <ListIcon as={MdCheckCircle} color="green.500" />
                    <Link href="https://github.com/ClaudioChametla" isExternal>
                      Git Hub <ExternalLinkIcon mx="2px" />
                    </Link>  
                  
                </ListItem>
              
                <ListItem>
                <ListIcon as={MdCheckCircle} color="green.500" />  
                <Link href="https://codepen.io/your-work" isExternal>
                      Code Pen <ExternalLinkIcon mx="2px" />
                </Link>  
                </ListItem>
        
                <ListItem>
                <ListIcon as={MdCheckCircle} color="green.500" />  
                  <Link href="https://www.linkedin.com/in/claudiochametla/" isExternal>
                      LinkedIn <ExternalLinkIcon mx="2px" />
                  </Link>  
                </ListItem>
            </List>
            <Center>
            
              <Image borderRadius="full"
               w="250px" 
               h="auto" 
               src="https://besthqwallpapers.com/Uploads/12-1-2021/151326/thumb2-github-purple-logo-4k-purple-brickwall-github-logo-social-networks.jpg" alt="Imagen Portafolio" />
          </Center>
            </VStack>
          
          </Box>
          <Box h="100px"/>
          {/*-----------------------------------FIN PROYECTO-------------------------------------------------------*/}
          
          
          {/*-----------------------------------HABILIDADES-------------------------------------------------------*/}    
          <Box  align="center"
              justify="center" h="700px" w="auto" >
          

          
          
          <Text fontSize="6xl" fontFamily="cursive" >Habilidades</Text>
         
          <Text fontSize="20px" >Algunos de las habilidades que domino en el entorno 
          de desarrollador web son las siguientes:  </Text>
          
          <br/>


          <VStack
              spacing={3}
            >

          <List spacing={1} alignContent="center">
              <Image
              borderRadius="full"  
              w="250px" 
              h="auto" 
              src="https://static.vecteezy.com/system/resources/previews/002/221/955/non_2x/coding-neon-programming-icon-vector.jpg" 
              alt="Imagen Habilidad coding" />
          
              <br/>
                <ListItem fontSize="2rem">
                     
                  Tecnologias:
                </ListItem>
                <ListItem>
                <ListIcon as={MdCheckCircle} color="green.500" />
                  HTML 5
                </ListItem>
                <ListItem>
                <ListIcon as={MdCheckCircle} color="green.500" />
                  CCS 3
                </ListItem>
                <ListItem>
                <ListIcon as={MdCheckCircle} color="green.500" />
                  JAVASCRIPT
                </ListItem>
                <ListItem>
                <ListIcon as={MdCheckCircle} color="green.500" />
                  REACT
                </ListItem>
                <ListItem>
                <ListIcon as={MdCheckCircle} color="green.500" />
                  NEXT JS
                </ListItem>
                
            </List>
            </VStack>
          </Box>
        {/*----------------------------------- FIN HABILIDADES-------------------------------------------------------*/}
        
        
        {/*-----------------------------------ACERCA DE MI-------------------------------------------------------*/}
        
          <Box 
              
              align="center"
              justify="center" bgImage="" h="600px" w="auto">
          
          <Text fontSize="6xl" fontFamily="cursive" > Acerca de mi </Text>
          
          <Center w="70%" flexDir="column">
          <Text fontSize="1rem" 
          
          >
            Soy un programador mexicano. <br/> 
            Nacido un Octubre en la Ciudad de México crecí en la en este lugar hasta los 10 años y desde 
            esa edad siempre habia tenido curiosidad por el mundo de la tecnologia e interes por las computadoras
             <br/>
            Fue hasta la edad de 13 años que mamá compro mi primera computadora. Con 512 MB de RAM y un procesador de
            900 Mhz empecé a conocer el mundo de Internet. Un dinosaurio pero fiel compañera. <br/>
            Desde niño mi computadora me sirvio para acercarme a diferentes softwares y juegos y al paso de los años
            elegí el camino de la computación y no fue hasta llegar a la universidad que tuve mi primer laptop y
            porfin programar mi primer <Text fontSize="25px"color="green"> Hello World. </Text>        
          </Text>
          <br/>
        </Center>
          <VStack
              divider={<StackDivider/>}
              spacing={1}
            >
              
              <Image
              borderRadius="full"  
              w="250px" 
              h="auto" 
              src="https://st2.depositphotos.com/14128164/42736/v/600/depositphotos_427361636-stock-illustration-beautiful-colorful-illustration-with-shiny.jpg" 
              alt="Imagen Habilidad coding" />
            </VStack>

            
          </Box>
        
        {/*-----------------------------------FIN ACERCA DE MI-------------------------------------------------------*/}
          
        </VStack>
      
      
      <Box h="100px"/>
        
      </main>

      <footer>

      


        <HStack 
         
         bgGradient="linear(to-r, blue.700, pink.500)"
        /*bgImage="https://upload.wikimedia.org/wikipedia/commons/4/4c/Digital_rain_banner.gif"*/
        h="250px"
        w="auto"
        spacing={10}
        justify="center"
        
        >
          <Image  
              borderRadius="full"
              w="200px" 
              h="auto" 
              src="https://scontent.fmex33-1.fna.fbcdn.net/v/t1.6435-9/83245201_1561723720649296_5245982117438947328_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=174925&_nc_eui2=AeEjX_e4IFK2KtFu_DCgCoDWsd5Lk4ZH8ICx3kuThkfwgDXIDJFvNvd9uealUdNRWXZAOhbUiKx7sdzwehukhx5-&_nc_ohc=YqH_rrENSSQAX8PCaQj&_nc_ht=scontent.fmex33-1.fna&oh=7f01c79bf39e65c9ff120bc45a6192d6&oe=61412457" 
              alt="claudiofooterfoto" />

              
              <List spacing={2} color="white" fontSize="20px" >
              
              <ListItem>
              <ListIcon as={MdCheckCircle} color="green.500" /> 

                Correo:
              </ListItem>
            
              <ListItem>
              <ListIcon as={MdCheckCircle} color="green.500" /> 
                clauchametla.777@gmail.com
              </ListItem>
            
              <ListItem>
              <ListIcon as={MdCheckCircle} color="green.500" /> 
                Telefono:
              </ListItem>
      
              <ListItem>
              <ListIcon as={MdCheckCircle} color="green.500" /> 
                56 15 64 49 57
              </ListItem>
          </List>

          <Avatar name="Claudio" src="https://bit.ly/broken-link" />
          <Text fontSize="2rem" fontFamily="monospace" color="white"> 
              Claudio Chametla Torres 
              
              </Text>
        

          
          
          
        </HStack>
  
      
      </footer>


      
    </Stack>
  )
}
