import Head from 'next/head'

import { useMediaQuery, Stack,Box, Center } from "@chakra-ui/react"

import NavBar from '../components/NavBar'
import Hero from '../components/Hero'
import Bienvenido from '../components/sections/Bienvenido'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <Stack>
      <Head >
        <title>Mi portafolio</title>
        <meta name="myportfolioproect" content="Generated by next app and created by Claudio Chametla" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
        <Center w="100%" flexDir="column"> 
          <Hero/>
          <Bienvenido/>
        </Center>
      <Footer/>
    </Stack>
  )
}
